server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Velog-Clone-Project/config-repo.git
          default-label: main
#          search-paths: ?

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health