server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Velog-Clone-Project/config-repo.git
          default-label: main
#          search-paths: ?
